# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1hUfbGWcUzMyVogaQanBLau5JShFDEX
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Titanic-Dataset.csv')

print(df.head())
print(df.info())
print(df.describe())
print(df.isnull().sum())

df['Age'].fillna(df['Age'].median(), inplace=True)
df['Fare'].fillna(df['Fare'].median(), inplace=True)
df.drop(columns=['Cabin'], inplace=True)
df.dropna(inplace=True)

df.hist(figsize=(10, 8))
plt.tight_layout()
plt.show()

sns.boxplot(x='Survived', y='Age', data=df)
plt.show()

sns.boxplot(x='Pclass', y='Fare', data=df)
plt.show()

numeric_df = df.select_dtypes(include=['number'])
corr = numeric_df.corr()
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.show()

sns.pairplot(df[['Survived', 'Pclass', 'Age', 'Fare']])
plt.show()

print(df.skew(numeric_only=True))